// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: report.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReportGenerator_GeneratePdfReport_FullMethodName = "/report.ReportGenerator/GeneratePdfReport"
)

// ReportGeneratorClient is the client API for ReportGenerator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReportGeneratorClient interface {
	GeneratePdfReport(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error)
}

type reportGeneratorClient struct {
	cc grpc.ClientConnInterface
}

func NewReportGeneratorClient(cc grpc.ClientConnInterface) ReportGeneratorClient {
	return &reportGeneratorClient{cc}
}

func (c *reportGeneratorClient) GeneratePdfReport(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, ReportGenerator_GeneratePdfReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReportGeneratorServer is the server API for ReportGenerator service.
// All implementations must embed UnimplementedReportGeneratorServer
// for forward compatibility.
type ReportGeneratorServer interface {
	GeneratePdfReport(context.Context, *ReportRequest) (*ReportResponse, error)
	mustEmbedUnimplementedReportGeneratorServer()
}

// UnimplementedReportGeneratorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReportGeneratorServer struct{}

func (UnimplementedReportGeneratorServer) GeneratePdfReport(context.Context, *ReportRequest) (*ReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GeneratePdfReport not implemented")
}
func (UnimplementedReportGeneratorServer) mustEmbedUnimplementedReportGeneratorServer() {}
func (UnimplementedReportGeneratorServer) testEmbeddedByValue()                         {}

// UnsafeReportGeneratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReportGeneratorServer will
// result in compilation errors.
type UnsafeReportGeneratorServer interface {
	mustEmbedUnimplementedReportGeneratorServer()
}

func RegisterReportGeneratorServer(s grpc.ServiceRegistrar, srv ReportGeneratorServer) {
	// If the following call panics, it indicates UnimplementedReportGeneratorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReportGenerator_ServiceDesc, srv)
}

func _ReportGenerator_GeneratePdfReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportGeneratorServer).GeneratePdfReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReportGenerator_GeneratePdfReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportGeneratorServer).GeneratePdfReport(ctx, req.(*ReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReportGenerator_ServiceDesc is the grpc.ServiceDesc for ReportGenerator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReportGenerator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "report.ReportGenerator",
	HandlerType: (*ReportGeneratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GeneratePdfReport",
			Handler:    _ReportGenerator_GeneratePdfReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "report.proto",
}
